classes: {
    combat: {
        style: {
            fill: red
            border-radius: 5
        }
        shape: hexagon
    }
    bonus: {
        style: {
            stroke: green
        }
    }
    chance: {
        style: {
            stroke: yellow
        }
    }
    negative: {
        style: {
            stroke: red
        }
    }
    chemin: {
        style: {
            stroke: green
            stroke-width: 5
        }
    }
    mort: {
        style: {
            fill: black
            font-color: white
        }
        shape: document
    }
    next: {
        shape: step
    }
    cochon: {
        icon: ./cochon.png
    }
}
