classes: {
    combat: {
        style: {
            fill: "#e63b19"
            border-radius: 5
        }
        shape: hexagon
    }
    bonus: {
        style: {
            stroke: green
        }
    }
    chance: {
        style: {
            stroke: "#b3ad04"
        }
    }
    negative: {
        style: {
            stroke: red
        }
    }
    chemin: {
        style: {
            stroke: green
            stroke-width: 5
        }
    }
    mort: {
        style: {
            fill: black
            font-color: white
        }
        shape: document
    }
    next: {
        shape: step
    }
    cochon: {
        icon: ./cochon.png
    }
    fin: {
        shape: cloud
        style: {
            fill: "linear-gradient(#5ab812, #6ffa05)"
        }
    }
}
