title: Les Mystères de Salamonis {
    shape: text
    near: top-center
    style: {
        font-size: 55
        italic: true
    }
}

introduction -> decouverte -> ville -> auberge -> facultes -> missions -> apres missions  -> homme qui tremble
apres missions -> missions
apres missions -> reve
reve -> apres missions
